// Export all AdminDashboard components
export { default as NavigationTabs } from './NavigationTabs';
export { default as OverviewTab } from './OverviewTab';
export { default as EditTimetableModal } from './EditTimetableModal';
export { default as DepartmentsTab } from './DepartmentsTab';
export { default as CoursesTab } from './CoursesTab';
export { default as TeachersTab } from './TeachersTab';
export { default as RoomsTab } from './RoomsTab';
export { default as CourseModal } from './CourseModal';
export { default as TeacherModal } from './TeacherModal';
export { default as RoomModal } from './RoomModal';
export { default as AdminProfileModal } from './AdminProfileModal';
export { default as ChangePasswordModal } from './ChangePasswordModal';
export { default as AddAdminModal } from './AddAdminModal';
export { default as DeleteConfirmModal } from './DeleteConfirmModal';
export { default as SettingsTab } from './SettingsTab';
export { default as SlotModal } from './SlotModal';
export { default as TimetablesTab } from './TimetablesTab';
export { default as TimetableViewTab } from './TimetableViewTab';
